### ISSUE TITLE
new icon

### ISSUE THREAD

**Issue by luthfirangers** [mohsenoid/itag#1]
Hi @mohsenoid , I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by mohsenoid** [comment]
Dear @luthfirangers, thanks for your suggestion.
If you are interested in doing it, feel free and contribute. You can also add your name and handle to the ReadMe file if you like.
